/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SENSOR_PACKET_HEADER, sensor_packet_header_t, AUTO)


PB_BIND(LUX_PACKET, lux_packet_t, 2)


PB_BIND(LUX_PACKET_PAYLOAD, lux_packet_payload_t, AUTO)




