# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: svc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import message_pb2 as message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tsvc.proto\x1a\rmessage.proto\"\x99\x01\n\rSubmitPackets\x12\"\n\x0bsensor_data\x18\x01 \x03(\x0b\x32\r.SensorPacket\x12!\n\x04meta\x18\x03 \x01(\x0b\x32\x13.SubmitPackets.Meta\x1a;\n\x04Meta\x12\r\n\x05\x65poch\x18\x01 \x01(\x01\x12\x16\n\tphone_uid\x18\x02 \x01(\rH\x00\x88\x01\x01\x42\x0c\n\n_phone_uidJ\x04\x08\x02\x10\x03\x62\x06proto3')



_SUBMITPACKETS = DESCRIPTOR.message_types_by_name['SubmitPackets']
_SUBMITPACKETS_META = _SUBMITPACKETS.nested_types_by_name['Meta']
SubmitPackets = _reflection.GeneratedProtocolMessageType('SubmitPackets', (_message.Message,), {

  'Meta' : _reflection.GeneratedProtocolMessageType('Meta', (_message.Message,), {
    'DESCRIPTOR' : _SUBMITPACKETS_META,
    '__module__' : 'svc_pb2'
    # @@protoc_insertion_point(class_scope:SubmitPackets.Meta)
    })
  ,
  'DESCRIPTOR' : _SUBMITPACKETS,
  '__module__' : 'svc_pb2'
  # @@protoc_insertion_point(class_scope:SubmitPackets)
  })
_sym_db.RegisterMessage(SubmitPackets)
_sym_db.RegisterMessage(SubmitPackets.Meta)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SUBMITPACKETS._serialized_start=29
  _SUBMITPACKETS._serialized_end=182
  _SUBMITPACKETS_META._serialized_start=117
  _SUBMITPACKETS_META._serialized_end=176
# @@protoc_insertion_point(module_scope)
