/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SENSOR_PACKET_HEADER, sensor_packet_header_t, AUTO)


PB_BIND(LUX_PACKET, lux_packet_t, 2)


PB_BIND(LUX_PACKET_PAYLOAD, lux_packet_payload_t, AUTO)


PB_BIND(SGP_PACKET, sgp_packet_t, 2)


PB_BIND(SGP_PACKET_PAYLOAD, sgp_packet_payload_t, AUTO)


PB_BIND(BME_PACKET, bme_packet_t, 2)


PB_BIND(BME_PACKET_PAYLOAD, bme_packet_payload_t, AUTO)


PB_BIND(BLINK_SATURATION_SETTINGS, blink_saturation_settings_t, AUTO)


PB_BIND(BLINK_BYTE_PAYLOAD, blink_byte_payload_t, 2)


PB_BIND(BLINK_HIGH_RES_PAYLOAD, blink_high_res_payload_t, 2)


PB_BIND(BLINK_PACKET, blink_packet_t, 2)


PB_BIND(SHT_PACKET, sht_packet_t, 2)


PB_BIND(SHT_PACKET_PAYLOAD, sht_packet_payload_t, AUTO)


PB_BIND(SPEC_PACKET, spec_packet_t, 2)


PB_BIND(SPEC_PACKET_PAYLOAD, spec_packet_payload_t, AUTO)


PB_BIND(THERM_PACKET, therm_packet_t, 2)


PB_BIND(THERM_PACKET_PAYLOAD, therm_packet_payload_t, AUTO)


PB_BIND(IMU_ACCEL_SETTINGS, imu_accel_settings_t, AUTO)


PB_BIND(IMU_GYRO_SETTINGS, imu_gyro_settings_t, AUTO)


PB_BIND(IMU_PACKET, imu_packet_t, 2)


PB_BIND(IMU_PACKET_PAYLOAD, imu_packet_payload_t, 2)


PB_BIND(MIC_PACKET, mic_packet_t, 2)


PB_BIND(MIC_PACKET_PAYLOAD, mic_packet_payload_t, 2)


PB_BIND(SENSOR_PACKET, sensor_packet_t, 2)


PB_BIND(AIR_SPEC_COLORS, air_spec_colors_t, AUTO)


PB_BIND(AIR_SPEC_COLOR_POSITION, air_spec_color_position_t, AUTO)


PB_BIND(LIGHT_CONTROL_PACKET, light_control_packet_t, AUTO)


PB_BIND(SENSOR_CONTROL, sensor_control_t, AUTO)


PB_BIND(LUX_SENSOR_CONFIG, lux_sensor_config_t, AUTO)


PB_BIND(SGP_SENSOR_CONFIG, sgp_sensor_config_t, AUTO)


PB_BIND(BME_SENSOR_CONFIG, bme_sensor_config_t, AUTO)


PB_BIND(COLOR_SENSOR_CONFIG, color_sensor_config_t, AUTO)


PB_BIND(THERMOPILE_SENSOR_CONFIG, thermopile_sensor_config_t, AUTO)


PB_BIND(BLINK_SENSOR_CONFIG, blink_sensor_config_t, AUTO)


PB_BIND(MIC_SENSOR_CONFIG, mic_sensor_config_t, AUTO)


PB_BIND(HUMIDITY_SENSOR_CONFIG, humidity_sensor_config_t, AUTO)


PB_BIND(IMU_SENSOR_CONFIG, imu_sensor_config_t, AUTO)


PB_BIND(SENSOR_CONFIG, sensor_config_t, AUTO)


PB_BIND(DFU_MODE, dfu_mode_t, AUTO)


PB_BIND(BLUE_GREEN_TRANSITION, blue_green_transition_t, AUTO)


PB_BIND(RED_FLASH_TASK, red_flash_task_t, AUTO)


PB_BIND(AIR_SPEC_CONFIG_HEADER, air_spec_config_header_t, AUTO)


PB_BIND(AIR_SPEC_CONFIG_PACKET, air_spec_config_packet_t, AUTO)


PB_BIND(SYSTEM_STATE, system_state_t, 2)

















